"""
Generate data/artworks.csv from data/art_auction_dataset.csv.

For each unique artwork_id in the sales dataset, emit one artwork row with
realistic metadata. Where possible, real well-known works of each artist are
used; filler entries are stylistically consistent with the artist's body of
work and constrained so year_created <= earliest sale_date for that id.

Run:
    uv run python scripts/gen_artworks.py
"""
from __future__ import annotations

import csv
import random
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SALES_CSV = ROOT / "data" / "art_auction_dataset.csv"
OUT_CSV = ROOT / "data" / "artworks.csv"

# Deterministic generation
random.seed(42)

# ────────────────────────────────────────────────────────────────────────────
# Per-artist data
#
# `real_works`: tuples of (title, year, medium, dims_cm, description, style, context, owners)
# `filler` settings drive synthetic but plausible entries beyond real_works
# ────────────────────────────────────────────────────────────────────────────

ARTIST_DATA: dict[str, dict] = {
    "Banksy": {
        "artist_id": "ART_BNK",
        "real_works": [
            ("Girl with Balloon", 2002, "Stencil and spray paint on canvas", "100x100",
             "Œuvre iconique représentant une fillette tendant la main vers un ballon en forme de cœur. Image la plus reconnue de l'artiste.",
             "Pochoir avec gestion des nuances, signature Banksy",
             "Créée à Londres, devenue symbole mondial de Banksy. Édition autodestruction Sotheby's 2018.",
             "Tate Modern (étude), Collection Lazarides, divers anonymes"),
            ("Love is in the Air (Flower Thrower)", 2003, "Stencil and spray paint", "70x50",
             "Manifestant masqué lançant un bouquet de fleurs au lieu d'un cocktail Molotov. Détournement pacifiste.",
             "Pochoir politique subversif",
             "Mur de séparation Bethléem, série Palestine. Référence absolue du travail engagé de Banksy.",
             "Collections privées multiples"),
            ("Devolved Parliament", 2009, "Oil on canvas", "274x426",
             "Chambre des Communes peuplée de chimpanzés. Œuvre la plus chère de Banksy à 9,9M£ chez Sotheby's 2019.",
             "Peinture à l'huile narrative",
             "Exposée Bristol Museum 2009. Vendue durant le débat Brexit, charge politique maximale.",
             "Bristol Museum (loan), collectionneur anonyme"),
            ("Game Changer", 2020, "Oil on canvas", "91x91",
             "Hommage aux soignants pendant la pandémie, enfant jouant avec figurine d'infirmière en super-héroïne.",
             "Hommage figuratif",
             "Donnée à Southampton Hospital, vendue 16,7M£ chez Christie's 2021 au profit du NHS.",
             "Southampton General Hospital (origine), collection privée"),
            ("Show Me the Monet", 2005, "Oil on canvas", "143x143",
             "Détournement du Pont Japonais de Monet, jonché de caddies abandonnés et cônes de signalisation.",
             "Détournement parodique d'œuvre classique",
             "Série Crude Oils. Vendu 7,55M£ chez Sotheby's 2020.",
             "Collection privée britannique"),
            ("Kissing Coppers", 2004, "Stencil on wall (transferred to canvas)", "210x150",
             "Deux policiers s'embrassant. Mural emblématique du Prince Albert pub à Brighton.",
             "Pochoir mural",
             "Originellement peint sur Brighton pub. Transféré sur toile pour vente.",
             "Pub Prince Albert (origine), collection privée US"),
            ("Slave Labour", 2012, "Stencil on wall (transferred)", "152x122",
             "Enfant cousant des drapeaux Union Jack pour le Jubilé de la Reine. Critique du travail des enfants.",
             "Mural politique transféré",
             "Wood Green, Londres. Retiré du mur pour mise en vente, polémique.",
             "Collection privée"),
            ("Mediterranean Sea View", 2017, "Triptych, oil on canvas", "60x90",
             "Triptyque de paysages marins idylliques où se mêlent gilets de sauvetage et migrants noyés.",
             "Détournement de paysage classique",
             "Donné à hôtel Walled Off Bethléem, vendu 2,2M£ Sotheby's 2020 pour fonds humanitaires.",
             "Collection privée"),
            ("Pulp Fiction", 2002, "Stencil and spray on canvas", "70x100",
             "Vincent et Jules pointant des bananes au lieu de pistolets. Détournement référence cinéma.",
             "Pochoir parodique",
             "Originellement peint sur mur Old Street, Londres. Retiré 2007.",
             "Collections privées"),
            ("Napalm", 2004, "Screenprint, edition of 150", "70x50",
             "Phan Thi Kim Phuc tenue par Mickey Mouse et Ronald McDonald. Critique impérialisme américain.",
             "Sérigraphie politique",
             "Référence directe à la photo Vietnam de Nick Ut 1972.",
             "Diverses collections privées"),
            ("Mona Lisa with Bazooka", 2000, "Stencil on canvas", "85x60",
             "Joconde portant un lance-roquettes. Détournement classique.",
             "Pochoir subversif",
             "Première période Banksy, série de détournements muséaux.",
             "Collection privée"),
            ("Trolley Hunters", 2006, "Stencil on canvas", "150x200",
             "Homme préhistorique chassant un caddie de supermarché. Critique de la société de consommation.",
             "Pochoir narratif",
             "Œuvre majeure exposée Barely Legal, Los Angeles, 2006.",
             "Collection privée"),
            ("Christ with Shopping Bags", 2004, "Stencil and spray on canvas", "100x70",
             "Christ crucifié portant des sacs de courses. Critique commercialisation des fêtes religieuses.",
             "Pochoir polémique",
             "Edition limitée tirée à 82 exemplaires.",
             "Collections privées"),
            ("Bomb Hugger", 2003, "Stencil on canvas", "60x80",
             "Petite fille embrassant tendrement une bombe.",
             "Pochoir antimilitariste",
             "Symbole du registre antimilitariste de Banksy.",
             "Collections privées"),
            ("Girl with Pearl Earring", 2014, "Stencil on wall (Bristol)", "300x200",
             "Détournement Vermeer, perle remplacée par alarme antivol installée sur le mur.",
             "Mural détourné",
             "Bristol Harbourside, devenue attraction touristique.",
             "Mur public Bristol"),
        ],
        "filler_titles": [
            "Untitled (Stencil)", "Spray Print", "Rat Series", "Police Series",
            "Untitled (Edition)", "Wall Fragment", "Studio Print", "Sprayed Canvas",
        ],
        "filler_mediums": ["Stencil and spray on canvas", "Screenprint, signed edition",
                           "Spray paint on metal", "Stencil on plywood"],
        "filler_dims": ["50x70", "70x100", "100x150", "60x80", "30x40"],
        "filler_style": "Pochoir et spray, signature Banksy",
        "filler_year_range": (1998, 2022),
        "filler_owners_pool": ["Lazarides Collection", "Pest Control archives",
                               "Collection privée britannique", "Collection privée US",
                               "Sotheby's archives"],
    },
    "KAWS": {
        "artist_id": "ART_KWS",
        "real_works": [
            ("The KAWS Album", 2005, "Acrylic on canvas", "101x101",
             "Détournement de la pochette Sgt. Pepper des Beatles avec figures Companion. Vendu 14,8M$ Sotheby's HK 2019.",
             "Pop figuratif graphique",
             "Référence centrale au pop art post-numérique. Record d'enchères de l'artiste.",
             "Collection privée asiatique"),
            ("Companion (Resting Place)", 2013, "Bronze sculpture", "180 cm height",
             "Sculpture monumentale du personnage Companion en position assise, tête baissée.",
             "Sculpture monumentale en bronze",
             "Déclinée en plusieurs tailles, présente dans collections muséales.",
             "Brooklyn Museum, Modern Art Museum Fort Worth"),
            ("Untitled (KIMPSONS)", 2002, "Acrylic on canvas", "81x81",
             "Détournement de la famille Simpson avec yeux croisés signature KAWS.",
             "Pop appropriation cartoon",
             "Série KIMPSONS, l'un des premiers détournements iconiques.",
             "Collection privée"),
            ("BFF (Pink)", 2017, "Plush sculpture, edition", "131 cm",
             "Peluche surdimensionnée du personnage BFF en rose.",
             "Sculpture textile éditionnée",
             "Edition limitée, vendue chez Phillips et Sotheby's.",
             "Collections privées multiples"),
            ("Final Days", 2013, "Bronze, edition of 25", "92x52x32",
             "Sculpture Companion gisant, série méditative sur la mort.",
             "Sculpture en bronze",
             "Présentée dans plusieurs expositions monographiques.",
             "Collections privées"),
            ("Holiday Hong Kong", 2019, "Inflatable installation", "37 meters",
             "Installation gonflable géante du Companion flottant dans le port de Hong Kong.",
             "Installation événementielle",
             "Documentée et reproduite en éditions limitées.",
             "AllRightsReserved (production)"),
            ("Companion Passing Through", 2018, "Painted bronze", "183x122x102",
             "Sculpture Companion accompagné d'une version miniature, thème de la transmission.",
             "Sculpture peinte en bronze",
             "Edition de 3, présente Pace Gallery.",
             "Collections institutionnelles"),
            ("Untitled (CHUM)", 2010, "Acrylic on canvas", "152x122",
             "Détournement du Michelin Man avec stylisation KAWS.",
             "Acrylique pop",
             "Personnage CHUM récurrent dans le travail de KAWS.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Companion", "BFF Edition", "CHUM Painting", "Untitled (Skull)",
            "TAKE", "What Party Edition", "Holiday Print", "KAWS Album Print",
        ],
        "filler_mediums": ["Acrylic on canvas", "Screenprint, edition", "Painted vinyl figure", "Bronze sculpture"],
        "filler_dims": ["81x81", "101x101", "152x122", "30x30 (figure)"],
        "filler_style": "Pop figuratif graphique post-numérique",
        "filler_year_range": (2000, 2022),
        "filler_owners_pool": ["AllRightsReserved", "Galerie Perrotin",
                               "Collection privée asiatique", "Collection privée US"],
    },
    "Invader": {
        "artist_id": "ART_INV",
        "real_works": [
            ("PA_1300 (Brain Wash)", 2014, "Tile mosaic on panel", "50x70",
             "Invasion en mosaïque carrelage, série Paris.",
             "Mosaïque pixel art",
             "Installation Paris 13e arrondissement, transférée sur panneau pour collection.",
             "Collections privées"),
            ("Rubikcubist Mona Lisa", 2008, "Rubik's cubes on panel", "80x60",
             "Portrait de la Joconde réalisé en cubes Rubik. Pratique signature de l'artiste.",
             "Rubikcubisme",
             "Œuvre majeure de la série Rubikcubist.",
             "Collection privée"),
            ("Space One (LDN_50)", 2009, "Tile mosaic on aluminum", "60x90",
             "Space invader géant, série Londres.",
             "Mosaïque carrelage urbaine",
             "Londres East End, transférée pour vente.",
             "Collections privées"),
            ("PA_25", 2003, "Ceramic tiles on cement", "40x40",
             "Première vague d'invasions parisiennes, technique mosaïque rudimentaire.",
             "Mosaïque pixel art primitive",
             "Documentée Paris 5e arrondissement.",
             "Collection privée"),
            ("Alias HK_58", 2014, "Tile mosaic", "70x70",
             "Invasion Hong Kong, déclinaison locale du programme.",
             "Mosaïque pixel art",
             "Programme Hong Kong, ville la plus densément 'invadée' d'Asie.",
             "Collection privée HK"),
            ("Space One Lyon", 2010, "Tile mosaic on board", "55x55",
             "Pixel art urbain série Lyon.",
             "Mosaïque pixel art",
             "Programme Lyon.",
             "Collection privée"),
            ("Invader Was Here", 2018, "Mixed media", "100x100",
             "Détournement carte du monde signée Invader sur les villes invadées.",
             "Carte murale conceptuelle",
             "Présentée Over The Influence Hong Kong.",
             "Collection privée"),
        ],
        "filler_titles": [
            "PA_", "LDN_", "HK_", "NY_", "TK_", "Alias", "Rubik Print", "Space Two",
        ],
        "filler_mediums": ["Tile mosaic on panel", "Aliases (resin reproduction)",
                           "Rubik's cubes on panel", "Print on paper, signed edition"],
        "filler_dims": ["40x40", "60x90", "80x60", "100x100"],
        "filler_style": "Mosaïque pixel art, héritage 8-bit",
        "filler_year_range": (2000, 2022),
        "filler_owners_pool": ["Galerie Le Feuvre", "Collection privée",
                               "Over The Influence Gallery"],
    },
    "Mr. Brainwash": {
        "artist_id": "ART_MRB",
        "real_works": [
            ("Madonna with Child", 2010, "Mixed media on paper", "100x70",
             "Hommage Madonna en mère, technique collage et peinture.",
             "Pop street art mixte",
             "Période post-Exit Through The Gift Shop.",
             "Collection privée"),
            ("Einstein Live the Life", 2011, "Mixed media on canvas", "150x100",
             "Portrait d'Einstein avec slogan inspirationnel, signature MBW.",
             "Street pop figuratif",
             "Edition limitée à 50 exemplaires.",
             "Collections privées"),
            ("Charlie Chaplin", 2009, "Stencil and spray on canvas", "80x60",
             "Hommage Chaplin série Hollywood Icons.",
             "Pochoir et acrylique",
             "Série Icons, plusieurs déclinaisons.",
             "Collection privée"),
            ("Banksy Thrower (Tribute)", 2013, "Mixed media on board", "100x80",
             "Hommage direct au Flower Thrower de Banksy, signature MBW typique.",
             "Pop appropriation",
             "Critiqué comme appropriation, vendu malgré tout.",
             "Collection privée"),
            ("Marilyn Pop", 2010, "Acrylic and silkscreen", "90x90",
             "Détournement Marilyn façon Warhol avec drips MBW.",
             "Pop hommage Warhol",
             "Style appropriationiste assumé.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Life is Beautiful", "Pop Heroes", "Splatter Series",
            "Untitled (Stencil)", "Mixed Media on Wood", "Spray on Canvas",
            "Hollywood Icons Series", "Vinyl Edition",
        ],
        "filler_mediums": ["Mixed media on canvas", "Spray and stencil on board",
                           "Silkscreen with hand-finishing", "Acrylic on aluminum"],
        "filler_dims": ["80x60", "100x100", "120x90", "60x60"],
        "filler_style": "Mixed media pop, héritage Warhol et Banksy",
        "filler_year_range": (2008, 2022),
        "filler_owners_pool": ["Collection privée US", "Collection privée européenne",
                               "Mr. Brainwash Studio archives"],
    },
    "Shepard Fairey": {
        "artist_id": "ART_SHF",
        "real_works": [
            ("Hope (Obama)", 2008, "Screenprint on paper", "61x91",
             "Portrait emblématique d'Obama campagne 2008, devenu icône politique mondiale.",
             "Sérigraphie politique",
             "Œuvre la plus connue de Fairey, controverse droits d'auteur AP.",
             "Smithsonian National Portrait Gallery (un exemplaire)"),
            ("Obey Giant", 1989, "Screenprint", "60x60",
             "Sticker original André the Giant Has a Posse, fondation du mouvement Obey.",
             "Sérigraphie street",
             "Œuvre fondatrice de la pratique Fairey.",
             "Collections privées multiples"),
            ("Peace Goddess", 2007, "Mixed media on paper", "100x70",
             "Figure pacifiste signature, série Peace.",
             "Stencil et collage",
             "Série Peace Goddess déclinée en plusieurs versions.",
             "Collection privée"),
            ("We the People", 2017, "Screenprint", "60x90",
             "Série de portraits multiculturels en réponse à l'élection Trump.",
             "Sérigraphie politique",
             "Œuvre virale, distribuée gratuitement dans manifestations.",
             "Diverses collections institutionnelles"),
            ("Make Art Not War", 2005, "Screenprint", "60x90",
             "Slogan iconique antimilitariste avec figure soldat-fleur.",
             "Sérigraphie engagée",
             "Edition limitée distribuée au profit de causes humanitaires.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Obey Eye", "Power & Glory", "Damaged", "Imperial Glory",
            "Floral Star", "Liberté Print", "Vote Print", "Stencil Series",
        ],
        "filler_mediums": ["Screenprint on paper, signed edition",
                           "Mixed media stencil on canvas", "Spray paint on board",
                           "Acrylic and silkscreen on canvas"],
        "filler_dims": ["60x90", "100x70", "120x80", "75x100"],
        "filler_style": "Propaganda esthétique street, palette rouge-noir-crème",
        "filler_year_range": (1995, 2022),
        "filler_owners_pool": ["Obey Giant Studio", "Collections privées US",
                               "Peres Projects archives"],
    },
    # ───── BLUE CHIP ─────
    "Picasso": {
        "artist_id": "ART_PCB",
        "real_works": [
            ("Femme assise au chapeau", 1941, "Huile sur toile", "116x89",
             "Portrait cubiste analytique tardif, période Occupation.",
             "Cubisme analytique tardif",
             "Peinte à Paris durant l'Occupation, malgré les restrictions imposées par le régime nazi.",
             "Musée Picasso Paris, anciennement Collection Kahnweiler"),
            ("Femmes d'Alger (Version O)", 1955, "Huile sur toile", "114x146",
             "Quinzième et dernière version de la série hommage à Delacroix. Vendue 179M$ Christie's 2015 (record monde à l'époque).",
             "Cubisme expressif tardif",
             "Hommage final à Delacroix, dernière version O d'une série de 15.",
             "Collection Ganz, anciennement collection Hamad Al Thani"),
            ("Garçon à la pipe", 1905, "Huile sur toile", "100x82",
             "Période rose, portrait emblématique. Vendu 104M$ Sotheby's 2004.",
             "Période rose",
             "Représente un jeune ouvrier parisien, modèle récurrent de Picasso.",
             "Collection Whitney, anciennement Greentree Foundation"),
            ("Le Rêve", 1932, "Huile sur toile", "130x97",
             "Portrait sensuel de Marie-Thérèse Walter. Vendu 155M$ en 2013.",
             "Période sensuelle Marie-Thérèse",
             "Marie-Thérèse Walter, muse et amante.",
             "Collection Steve Wynn puis Steven Cohen"),
            ("Tête de femme (Dora Maar)", 1939, "Huile sur toile", "92x65",
             "Portrait cubiste de la photographe Dora Maar.",
             "Cubisme synthétique",
             "Dora Maar, photographe et compagne durant la Guerre d'Espagne.",
             "Collection privée, anciennement collection Maar"),
            ("Buste de femme au chapeau (Dora Maar)", 1941, "Huile sur toile", "65x54",
             "Portrait cubiste tardif de Dora Maar avec chapeau.",
             "Cubisme tardif",
             "Période d'instabilité émotionnelle, fin de la liaison avec Dora Maar.",
             "Collection privée"),
            ("Femme au chat assise", 1964, "Huile sur toile", "146x114",
             "Œuvre tardive, portrait de Jacqueline Roque assise avec un chat.",
             "Période Jacqueline",
             "Jacqueline Roque, dernière compagne et muse de Picasso.",
             "Collection privée"),
            ("Le Jardin (Mougins)", 1971, "Huile sur toile", "130x162",
             "Période ultime à Mougins, paysage stylisé.",
             "Période tardive expressive",
             "Mougins, dernière résidence de Picasso.",
             "Collection privée"),
            ("Mousquetaire à la pipe", 1968, "Huile sur toile", "146x114",
             "Série Mousquetaires des dernières années.",
             "Période Mougins, série Mousquetaires",
             "Inspirée par Rembrandt et la peinture du Siècle d'Or.",
             "Collection privée"),
            ("Nu couché sur fond bleu", 1955, "Huile sur toile", "114x146",
             "Nu de Jacqueline Roque sur fond bleu intense.",
             "Période Cannes, Jacqueline",
             "Période La Californie (Cannes).",
             "Collection privée"),
            ("Tête de femme (Marie-Thérèse)", 1932, "Huile sur toile", "65x54",
             "Portrait sculptural de Marie-Thérèse Walter.",
             "Période Boisgeloup, sculpturale",
             "Boisgeloup, période sculpturale.",
             "Collection privée"),
            ("Femme dans un fauteuil", 1956, "Huile sur toile", "146x114",
             "Portrait Jacqueline assise.",
             "Période Cannes",
             "La Californie, Cannes.",
             "Collection privée"),
            ("L'Aubade", 1942, "Huile sur toile", "195x265",
             "Composition double, femme étendue et musicienne, période Occupation.",
             "Cubisme narratif Occupation",
             "Paris, période Guerre. Don au Centre Pompidou.",
             "Centre Pompidou Paris"),
            ("Femme à la résille", 1949, "Huile sur toile", "100x81",
             "Portrait Françoise Gilot avec résille pour cheveux.",
             "Période Vallauris",
             "Vallauris, période Françoise Gilot.",
             "Collection privée"),
            ("Atelier à Cannes", 1957, "Huile sur toile", "114x146",
             "Vue intérieure de l'atelier La Californie à Cannes.",
             "Période Cannes",
             "La Californie, Cannes.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Tête de femme", "Nature morte au verre", "Étude pour mousquetaire",
            "Femme couchée", "Composition", "Buste d'homme", "Étude au crayon",
            "Le peintre et son modèle", "Portrait de Jacqueline", "Nu",
        ],
        "filler_mediums": ["Huile sur toile", "Crayon sur papier", "Aquarelle et encre",
                           "Lithographie, édition signée", "Eau-forte et pointe sèche"],
        "filler_dims": ["65x54", "92x73", "100x81", "130x97", "146x114"],
        "filler_style": "Cubisme et périodes successives, palette variable",
        "filler_year_range": (1901, 1972),
        "filler_owners_pool": ["Musée Picasso Paris", "Centre Pompidou",
                               "MoMA New York", "Tate Modern", "Collection Beyeler",
                               "Collections privées européennes"],
    },
    "Warhol": {
        "artist_id": "ART_WAR",
        "real_works": [
            ("Shot Sage Blue Marilyn", 1964, "Silkscreen and acrylic on canvas", "102x102",
             "Marilyn Monroe sur fond bleu sage. Vendue 195M$ Christie's 2022 (record Warhol).",
             "Sérigraphie pop",
             "Série Shot Marilyns, attribut de la perforation par balle. Record absolu de Warhol.",
             "Collection Brant puis collection privée"),
            ("Campbell's Soup Cans", 1962, "Synthetic polymer paint on canvas", "51x41 each (32 pieces)",
             "Série fondatrice du pop art, 32 boîtes de soupe, une par variété.",
             "Pop minimaliste sériel",
             "Première exposition pop décisive Ferus Gallery LA 1962.",
             "MoMA New York (collection complète)"),
            ("Mao", 1972, "Acrylic and silkscreen on canvas", "127x107",
             "Portrait Mao Zedong, série politique.",
             "Sérigraphie portrait politique",
             "Série déclinée en plusieurs tailles et coloris.",
             "Collections privées multiples, Tate Modern"),
            ("Liz #5 (Early Colored Liz)", 1963, "Silkscreen on canvas", "102x102",
             "Portrait Elizabeth Taylor, série Liz.",
             "Sérigraphie portrait star",
             "Période hommages aux stars hollywoodiennes.",
             "Collection privée"),
            ("Eight Elvises", 1963, "Silkscreen on canvas", "203x305",
             "Multiplication de l'image d'Elvis Presley en huit exemplaires.",
             "Sérigraphie sérielle",
             "Œuvre rare, vendue 100M$ en 2008.",
             "Collection privée européenne"),
            ("Self-Portrait", 1986, "Acrylic and silkscreen", "203x203",
             "Autoportrait au camouflage, dernière période.",
             "Sérigraphie auto-référentielle",
             "Période finale, peu après sa mort en 1987.",
             "Tate Modern, MoMA"),
            ("Diamond Dust Shoes", 1980, "Acrylic, silkscreen and diamond dust", "229x178",
             "Chaussures sur fond pailleté, série iconique.",
             "Sérigraphie avec poussière de diamants",
             "Commande Halston, popularité de la série années 80.",
             "Collections privées"),
            ("Flowers", 1964, "Acrylic and silkscreen on linen", "61x61",
             "Hibiscus stylisés, série déclinée en multiples couleurs.",
             "Sérigraphie pop florale",
             "Série dérivée d'une photo amateur, polémique droits d'auteur.",
             "Collections privées multiples"),
            ("Brillo Box", 1964, "Silkscreen on plywood", "44x43x35",
             "Cube reproduction des boîtes savon Brillo, sculpture conceptuelle.",
             "Sculpture pop",
             "Centre d'un débat philosophique majeur sur 'qu'est-ce que l'art'.",
             "Diverses institutions, collections privées"),
            ("Mick Jagger", 1975, "Silkscreen and graphite on paper", "110x74",
             "Série de portraits Mick Jagger commande des Stones.",
             "Sérigraphie portrait star",
             "Commande Mick Jagger pour la couverture Love You Live.",
             "Collections privées"),
            ("Jackie", 1964, "Acrylic and silkscreen on canvas", "51x41",
             "Portrait Jackie Kennedy après l'assassinat de JFK.",
             "Sérigraphie hommage politique",
             "Série répondant au traumatisme post-assassinat JFK.",
             "Collections privées"),
            ("Liz Taylor (Blue)", 1964, "Silkscreen on canvas", "102x102",
             "Variante coloriée de la série Liz.",
             "Sérigraphie portrait pop",
             "Période faste de la commande de portraits hollywoodiens.",
             "Collection privée"),
            ("Skull", 1976, "Acrylic and silkscreen on canvas", "183x203",
             "Crâne stylisé, série méditation sur la mort.",
             "Sérigraphie memento mori",
             "Série Skull, méditation sur la mortalité.",
             "Collections privées"),
            ("Chairman Mao (Pink)", 1973, "Silkscreen and acrylic on canvas", "127x107",
             "Variation rose de la série Mao.",
             "Sérigraphie politique pop",
             "Variation chromatique du portrait Mao.",
             "Collections privées"),
            ("Cow", 1966, "Wallpaper screenprint", "115x76",
             "Vache rose sur fond jaune, papier-peint sérigraphique.",
             "Sérigraphie décorative",
             "Conçu comme installation murale, exposition Castelli 1966.",
             "Diverses collections institutionnelles"),
        ],
        "filler_titles": [
            "Marilyn Variant", "Liz Variant", "Mao Series", "Self-Portrait Variant",
            "Flowers Series", "Cow Print", "Untitled (Polaroid Study)",
            "Skull Series", "Camouflage", "Dollar Sign", "Ladies and Gentlemen",
        ],
        "filler_mediums": ["Acrylic and silkscreen on canvas", "Silkscreen on paper, signed edition",
                           "Polaroid", "Acrylic, silkscreen and diamond dust"],
        "filler_dims": ["51x41", "102x102", "127x107", "183x203"],
        "filler_style": "Sérigraphie pop, palette saturée",
        "filler_year_range": (1962, 1986),
        "filler_owners_pool": ["The Andy Warhol Foundation", "MoMA",
                               "Tate Modern", "Whitney Museum",
                               "Collection Mugrabi", "Collections privées multiples"],
    },
    "Monet": {
        "artist_id": "ART_MON",
        "real_works": [
            ("Nymphéas (Series, 1916)", 1916, "Huile sur toile", "200x180",
             "Bassin aux nymphéas, fleurs flottantes sur l'eau du jardin de Giverny.",
             "Impressionnisme tardif, série Nymphéas",
             "Série emblématique réalisée à Giverny, environ 250 toiles.",
             "Musée d'Orsay, MoMA, Tate Modern, collections privées"),
            ("Meules au soleil", 1891, "Huile sur toile", "60x100",
             "Série meules de foin, étude lumière saisonnière. Vendue 110M$ Sotheby's 2019.",
             "Impressionnisme sériel",
             "Série Meules, 25 toiles capturant la lumière à différents moments.",
             "Collection privée, anciennement Bill Acquavella"),
            ("Le Bassin aux Nymphéas", 1919, "Huile sur toile", "100x200",
             "Pont japonais traversant le bassin de Giverny.",
             "Période ultime Giverny",
             "Période finale, vision proche de l'abstraction.",
             "Collections privées multiples"),
            ("La Cathédrale de Rouen, plein soleil", 1894, "Huile sur toile", "107x73",
             "Cathédrale de Rouen captée au plein soleil, série lumière.",
             "Impressionnisme sériel architectural",
             "Série de 30 vues de la cathédrale, expérience de la lumière.",
             "Musée d'Orsay"),
            ("Impression, soleil levant", 1872, "Huile sur toile", "48x63",
             "Œuvre fondatrice de l'impressionnisme, port du Havre au lever du jour.",
             "Œuvre fondatrice impressionnisme",
             "Première exposition impressionniste 1874, donne son nom au mouvement.",
             "Musée Marmottan Monet"),
            ("Femme à l'ombrelle", 1875, "Huile sur toile", "100x81",
             "Camille Monet et son fils Jean dans le jardin d'Argenteuil.",
             "Impressionnisme période argenteuil",
             "Camille Monet, première femme et muse.",
             "National Gallery of Art Washington"),
            ("Le Pont Japonais à Giverny", 1899, "Huile sur toile", "89x93",
             "Pont japonais série dédiée, vue de près.",
             "Impressionnisme série Giverny",
             "Pont créé spécifiquement par Monet pour le motif.",
             "Collections multiples"),
            ("Champ de coquelicots", 1873, "Huile sur toile", "50x65",
             "Camille et Jean Monet traversant un champ de coquelicots.",
             "Impressionnisme paysage",
             "Argenteuil, période bonheur familial.",
             "Musée d'Orsay"),
            ("Les Peupliers, vue d'ensemble", 1891, "Huile sur toile", "82x82",
             "Série peupliers, étude reflets dans la rivière Epte.",
             "Impressionnisme sériel",
             "Série Peupliers, 24 toiles, peupliers menacés d'abattage.",
             "Musée d'Orsay"),
            ("Le Parlement de Londres, soleil dans le brouillard", 1904, "Huile sur toile", "81x92",
             "Parlement vu de Londres traversé par la lumière dans le brouillard.",
             "Impressionnisme période Londres",
             "Série Londres, environ 100 toiles capturant le smog.",
             "Musée d'Orsay"),
            ("Vétheuil sous la neige", 1879, "Huile sur toile", "60x90",
             "Période Vétheuil hivernale.",
             "Impressionnisme paysage hivernal",
             "Vétheuil, période difficile suite à la maladie de Camille.",
             "Musée d'Orsay"),
            ("Les Falaises d'Étretat", 1885, "Huile sur toile", "65x81",
             "Falaise de l'Aiguille, vue caractéristique d'Étretat.",
             "Impressionnisme paysage marin",
             "Série Étretat, fascination pour la côte normande.",
             "Collections privées"),
            ("Soleil couchant à Lavacourt", 1880, "Huile sur toile", "100x150",
             "Coucher de soleil sur la Seine à Lavacourt.",
             "Impressionnisme paysage fluvial",
             "Période Vétheuil, paysage transitoire.",
             "Petit Palais Paris"),
            ("Le Jardin de l'artiste à Giverny", 1900, "Huile sur toile", "81x92",
             "Allée d'iris dans le jardin de Giverny.",
             "Impressionnisme jardin",
             "Jardin créé par Monet à Giverny dès 1883.",
             "Musée d'Orsay"),
            ("Bassin aux nymphéas, harmonie verte", 1899, "Huile sur toile", "89x93",
             "Variation chromatique verte du bassin aux nymphéas.",
             "Période Giverny",
             "Période d'expérimentation chromatique sur le motif unique.",
             "Musée d'Orsay"),
        ],
        "filler_titles": [
            "Nymphéas", "Meules", "Étude de cathédrale", "Vue de Giverny",
            "Le pont japonais", "Étretat", "Étang", "Vétheuil",
            "Argenteuil", "Étude impressionniste",
        ],
        "filler_mediums": ["Huile sur toile", "Pastel sur papier", "Étude au crayon"],
        "filler_dims": ["65x81", "81x100", "100x150", "60x90"],
        "filler_style": "Impressionnisme, palette pastel et touche divisée",
        "filler_year_range": (1865, 1926),
        "filler_owners_pool": ["Musée d'Orsay", "Musée Marmottan Monet",
                               "MoMA", "Tate Modern", "National Gallery Washington",
                               "Art Institute of Chicago", "Collections privées"],
    },
    "Basquiat": {
        "artist_id": "ART_BSQ",
        "real_works": [
            ("Untitled (Skull)", 1981, "Acrylic and oilstick on canvas", "207x176",
             "Crâne stylisé série Heads, œuvre majeure de la première période.",
             "Néo-expressionnisme, période Heads",
             "Période SAMO, première grande série de têtes/crânes.",
             "Collection privée, anciennement Eli Broad"),
            ("In This Case", 1983, "Acrylic and oilstick on canvas", "198x188",
             "Tête couronnée sur fond rouge intense. Vendue 93M$ Christie's 2021.",
             "Néo-expressionnisme période classique",
             "Période 1983, sommet créatif. Référence aux figures historiques noires.",
             "Collection privée, anciennement Giancarlo Giammetti"),
            ("Boxer Rebellion", 1983, "Acrylic and oilstick on canvas", "183x305",
             "Scène boxeurs anonymes, référence à la Boxer Rebellion chinoise.",
             "Néo-expressionnisme historique",
             "Période 1983, intérêt pour l'histoire des opprimés.",
             "Collection privée"),
            ("Versus Medici", 1982, "Acrylic and oilstick on canvas", "214x137",
             "Confrontation Basquiat / Médicis, dialogue art ancien et art noir.",
             "Néo-expressionnisme, période classique",
             "Modène, période première italienne.",
             "Collection privée, anciennement Mugrabi"),
            ("Dustheads", 1982, "Acrylic and oilstick on canvas", "214x214",
             "Deux têtes flottant sur fond noir, vendue 49M$ Christie's 2013.",
             "Néo-expressionnisme",
             "Inspiration drogue dans les rues de New York.",
             "Collection privée"),
            ("Defacement (The Death of Michael Stewart)", 1983, "Acrylic and marker on wood", "62x77",
             "Hommage à Michael Stewart, jeune graffeur tué par la police.",
             "Néo-expressionnisme politique",
             "Hommage au jeune graffeur Michael Stewart, drame personnel pour Basquiat.",
             "Collection Keith Haring estate, Guggenheim Museum"),
            ("Self-Portrait", 1984, "Acrylic and oilstick on canvas", "152x122",
             "Autoportrait stylisé, période apogée commerciale.",
             "Néo-expressionnisme auto-référentiel",
             "Période sommet de notoriété, contrats avec Mary Boone.",
             "Collection privée"),
            ("Hollywood Africans", 1983, "Acrylic and oilstick on canvas", "213x213",
             "Hollywood Africans, référence à la place des artistes noirs à Hollywood.",
             "Néo-expressionnisme politique",
             "Référence à Toxic et Rammelzee, collègues SAMO.",
             "Whitney Museum"),
            ("Notary", 1983, "Acrylic and oilstick on canvas", "180x401 (triptyque)",
             "Triptyque monumental sur le pouvoir bureaucratique.",
             "Néo-expressionnisme politique tryptique",
             "Période 1983, exposition Mary Boone.",
             "Daros Collection Suisse"),
            ("Untitled (Boxer)", 1982, "Acrylic and oilstick on canvas", "193x239",
             "Boxeur stylisé, référence à Sugar Ray Robinson.",
             "Néo-expressionnisme",
             "Référence aux héros sportifs noirs.",
             "Collection privée"),
            ("Trumpet", 1984, "Acrylic and oilstick on canvas", "152x152",
             "Trompette stylisée, référence au jazz et héritage musical noir.",
             "Néo-expressionnisme musical",
             "Période d'intérêt pour le jazz et Charlie Parker.",
             "Collection privée"),
            ("Charles the First", 1982, "Acrylic and oilstick on canvas", "198x158 (triptyque)",
             "Triptyque dédié à Charlie Parker.",
             "Néo-expressionnisme musical",
             "Charlie Parker, héros artistique de Basquiat.",
             "Collection privée"),
            ("Pegasus", 1987, "Acrylic and oilstick on canvas", "233x335",
             "Pégase et écriture dense, période finale.",
             "Néo-expressionnisme période finale",
             "Période fin 1987, peu avant la mort de Basquiat.",
             "Collections privées"),
            ("Riding with Death", 1988, "Acrylic on canvas", "249x289",
             "Squelette à cheval sur silhouette anonyme, dernière œuvre majeure.",
             "Néo-expressionnisme, dernière période",
             "Œuvre testamentaire, peu avant la mort en août 1988.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Untitled (Heads)", "Crown Series", "Famous Negro Athletes",
            "Untitled (Beak)", "Notary Study", "Untitled (Skull)", "King Series",
            "Untitled (Boxer)", "Discography",
        ],
        "filler_mediums": ["Acrylic and oilstick on canvas", "Mixed media on paper",
                           "Oilstick and crayon on paper", "Spray paint on wood"],
        "filler_dims": ["122x152", "152x152", "183x183", "213x213"],
        "filler_style": "Néo-expressionnisme, palette saturée et écriture dense",
        "filler_year_range": (1980, 1988),
        "filler_owners_pool": ["Whitney Museum", "Brooklyn Museum",
                               "Collection Mugrabi", "Collection Yusaku Maezawa",
                               "Collections privées internationales"],
    },
    "Giacometti": {
        "artist_id": "ART_GCM",
        "real_works": [
            ("L'Homme au doigt", 1947, "Bronze sculpture", "178x95x52",
             "Homme désignant l'horizon, œuvre emblématique d'après-guerre. Vendue 141M$ Christie's 2015.",
             "Sculpture existentialiste",
             "Période d'après-guerre, sommet créatif.",
             "Collections privées multiples"),
            ("L'Homme qui marche I", 1960, "Bronze sculpture", "180x27x97",
             "Sculpture monumentale, archétype de la silhouette giacomettienne. Vendue 104M$ Sotheby's 2010.",
             "Sculpture existentialiste tardive",
             "Commande Chase Manhattan Plaza, finalement non installée.",
             "Tate Modern, Centre Pompidou, MoMA"),
            ("Trois hommes qui marchent", 1948, "Bronze", "76x42x32",
             "Trois figures déambulant, sculpture groupée.",
             "Sculpture après-guerre",
             "Période d'expérimentation des relations spatiales.",
             "Collections multiples"),
            ("Femme de Venise V", 1956, "Bronze", "111x16x35",
             "Série Femmes de Venise pour la Biennale.",
             "Sculpture biennale 1956",
             "Pavillon français Biennale Venise 1956, série de 9.",
             "Collections multiples"),
            ("Diego (buste)", 1955, "Bronze", "39x18x15",
             "Buste de son frère Diego, modèle récurrent.",
             "Sculpture portrait familial",
             "Diego, frère cadet et modèle de toute une vie.",
             "Collections privées"),
            ("Le Chat", 1951, "Bronze", "32x81x14",
             "Chat allongé, étude animalière.",
             "Sculpture animalière",
             "Période d'expérimentation animalière.",
             "Collections multiples"),
            ("Le Chien", 1951, "Bronze", "47x100x15",
             "Chien errant, sculpture animalière complémentaire au Chat.",
             "Sculpture animalière",
             "Inspirée par les chiens errants observés à Paris.",
             "Collections multiples"),
            ("Tête de Diego", 1954, "Huile sur toile", "92x65",
             "Portrait peint de Diego, complément aux sculptures.",
             "Peinture portrait",
             "Diego, frère et modèle constant.",
             "Collections privées"),
            ("Caroline", 1962, "Huile sur toile", "100x65",
             "Portrait de Caroline, dernière compagne et muse.",
             "Peinture portrait période finale",
             "Caroline, période finale, muse des dernières années.",
             "Collections privées"),
            ("Annette assise", 1958, "Bronze", "80x36x53",
             "Annette, sa femme, assise.",
             "Sculpture portrait familial",
             "Annette Arm, épouse depuis 1949.",
             "Collections multiples"),
            ("L'Homme qui chavire", 1950, "Bronze", "60x33x14",
             "Figure en déséquilibre, métaphore existentielle.",
             "Sculpture existentialiste",
             "Période d'expérimentation des limites du corps debout.",
             "Collections multiples"),
            ("Buste de Diego (sur stèle)", 1957, "Bronze", "58x15x18",
             "Buste de Diego sur socle haut.",
             "Sculpture portrait",
             "Période d'apogée des bustes Diego.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Buste", "Tête sur socle", "Femme debout", "Homme qui marche (étude)",
            "Diego (variante)", "Annette (étude)", "Sculpture",
            "Étude au crayon", "Portrait dessiné",
        ],
        "filler_mediums": ["Bronze, édition", "Plâtre original",
                           "Crayon sur papier", "Huile sur toile"],
        "filler_dims": ["35x10x10", "60x20x15", "80x25x20", "120x35x40"],
        "filler_style": "Sculpture existentialiste filiforme",
        "filler_year_range": (1925, 1966),
        "filler_owners_pool": ["Fondation Giacometti Paris", "Tate Modern",
                               "Centre Pompidou", "MoMA", "Beyeler Foundation",
                               "Collections privées européennes"],
    },
    # ───── MODERN MASTERS ─────
    "Hockney": {
        "artist_id": "ART_HCK",
        "real_works": [
            ("Portrait of an Artist (Pool with Two Figures)", 1972, "Acrylic on canvas", "214x305",
             "Œuvre emblématique, double portrait piscine. Vendue 90,3M$ Christie's 2018.",
             "Pop figuratif, période californienne",
             "Période Los Angeles, sommet de la série piscines.",
             "Collection David Geffen, puis Joe Lewis"),
            ("A Bigger Splash", 1967, "Acrylic on canvas", "242x244",
             "Plongeon stylisé, signature de la période californienne.",
             "Pop figuratif californien",
             "Tate Britain, œuvre la plus reproduite de Hockney.",
             "Tate Britain"),
            ("Mr and Mrs Clark and Percy", 1971, "Acrylic on canvas", "213x305",
             "Portrait Ossie Clark et Celia Birtwell, leur chat Percy.",
             "Pop figuratif portrait",
             "Période Londres post-Californie.",
             "Tate Britain"),
            ("Pearblossom Highway", 1986, "Photomontage Polaroid", "198x282",
             "Photomontage Polaroid, route californienne.",
             "Photomontage cubiste",
             "Période expérimentation photographique, Joiners.",
             "Getty Museum"),
            ("Garrowby Hill", 1998, "Oil on canvas", "152x193",
             "Paysage Yorkshire, retour aux racines anglaises.",
             "Paysage Yorkshire",
             "Retour Hockney au Yorkshire fin années 90.",
             "Collection privée"),
            ("Bigger Trees Near Warter", 2007, "Oil on canvas", "457x1219 (50 panels)",
             "Paysage monumental, 50 toiles assemblées.",
             "Paysage Yorkshire monumental",
             "Tate Britain, donation Hockney.",
             "Tate Britain"),
            ("Rocky Mountains and Tired Indians", 1965, "Acrylic on canvas", "171x244",
             "Paysage parodique des Rocheuses.",
             "Pop période américaine",
             "Première période américaine.",
             "National Gallery of Scotland"),
            ("American Collectors (Fred and Marcia Weisman)", 1968, "Acrylic on canvas", "213x305",
             "Portrait des collectionneurs Weisman dans leur jardin.",
             "Pop figuratif portrait",
             "Période Los Angeles, portraits sociologiques.",
             "Art Institute of Chicago"),
            ("My Parents", 1977, "Oil on canvas", "183x183",
             "Portrait de ses parents Kenneth et Laura Hockney.",
             "Pop figuratif portrait",
             "Hommage parental, période transition.",
             "Tate Britain"),
            ("Sunbather", 1966, "Acrylic on canvas", "183x183",
             "Baigneur sur tapis bleu, série piscines.",
             "Pop figuratif californien",
             "Période piscines, Los Angeles.",
             "Museum Ludwig Cologne"),
            ("Beverly Hills Housewife", 1966, "Acrylic on canvas", "183x366",
             "Maîtresse de maison Beverly Hills, portrait sociologique.",
             "Pop figuratif portrait",
             "Période Los Angeles, observation sociale.",
             "Collection privée"),
            ("Two Boys in a Pool, Hollywood", 1965, "Acrylic on canvas", "152x152",
             "Deux jeunes hommes dans une piscine.",
             "Pop figuratif piscine",
             "Période Los Angeles, première série piscines.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Pool Series", "Yorkshire Landscape", "Joiners Series",
            "iPad Drawing", "Stage Design", "Domestic Scene",
            "Untitled (Pool)", "California View", "Garden Series",
        ],
        "filler_mediums": ["Acrylic on canvas", "Oil on canvas",
                           "iPad print, signed edition", "Photomontage Polaroid"],
        "filler_dims": ["152x152", "183x244", "214x305", "100x100"],
        "filler_style": "Pop figuratif, palette acidulée Californie",
        "filler_year_range": (1962, 2022),
        "filler_owners_pool": ["Tate Britain", "Museum Ludwig", "MoMA",
                               "Centre Pompidou", "Collection David Geffen",
                               "Collections privées internationales"],
    },
    "Richter": {
        "artist_id": "ART_RCH",
        "real_works": [
            ("Abstraktes Bild (1024-3)", 1990, "Oil on canvas", "200x320",
             "Tableau abstrait squeegee, série emblématique.",
             "Abstraction squeegee",
             "Période squeegee mature, signature de l'artiste.",
             "Collection privée, anciennement Eric Clapton"),
            ("Domplatz, Mailand", 1968, "Oil on canvas", "275x290",
             "Vue floutée de la place du Duomo Milan. Vendue 37M$ Sotheby's 2013.",
             "Photo-peinture, série Photo-Paintings",
             "Photo-peinture, technique signature de la période.",
             "Collection privée, anciennement Lehman Brothers"),
            ("Betty", 1988, "Oil on canvas", "102x72",
             "Portrait de sa fille Betty, dos retourné.",
             "Photo-peinture portrait familial",
             "Saint Louis Art Museum, œuvre fréquemment exposée.",
             "Saint Louis Art Museum"),
            ("Eis (Ice)", 1981, "Oil on canvas", "60x80",
             "Paysage glacé série Eis.",
             "Photo-peinture paysage",
             "Inspiration voyage Groenland 1972.",
             "Collection privée"),
            ("Ema (Akt auf einer Treppe)", 1966, "Oil on canvas", "200x130",
             "Portrait floutée de sa femme Ema descendant escalier.",
             "Photo-peinture, série Akt",
             "Référence directe à Marcel Duchamp.",
             "Museum Ludwig Cologne"),
            ("Cage (1-6)", 2006, "Oil on canvas", "300x300 (6 panels)",
             "Cycle abstrait dédié à John Cage.",
             "Abstraction tardive",
             "Tate Modern, série dédiée John Cage.",
             "Tate Modern"),
            ("Tante Marianne", 1965, "Oil on canvas", "120x130",
             "Portrait floutée de sa tante Marianne, victime nazisme.",
             "Photo-peinture mémoire familiale",
             "Mémoire familiale Allemagne nazie.",
             "Museum für Moderne Kunst Frankfurt"),
            ("18. Oktober 1977 (Cycle Baader-Meinhof)", 1988, "Oil on canvas", "(15 panels)",
             "Cycle peintures sur la mort des membres RAF en prison.",
             "Photo-peinture historique politique",
             "MoMA, cycle politique majeur.",
             "MoMA New York"),
            ("Wald (Forest)", 2005, "Oil on canvas", "200x320",
             "Forêt floutée série Wald.",
             "Photo-peinture paysage",
             "Période Wald, retour au paysage.",
             "Collections privées"),
            ("Strip", 2011, "Digital print on aluminum", "200x300",
             "Bandes colorées générées numériquement.",
             "Strip Paintings, période digitale",
             "Pratique numérique tardive, expansion abstraction.",
             "Diverses collections institutionnelles"),
            ("Lesende (Reader)", 1994, "Oil on canvas", "72x102",
             "Portrait Sabine lisant, photo-peinture.",
             "Photo-peinture portrait",
             "Sabine Moritz, sa troisième épouse et muse.",
             "Collection privée"),
            ("Helga Matura", 1966, "Oil on canvas", "60x80",
             "Photo-peinture inspirée d'une photo de presse.",
             "Photo-peinture presse",
             "Période usage des photos de presse.",
             "Museum Ludwig Cologne"),
        ],
        "filler_titles": [
            "Abstraktes Bild", "Wald Series", "Strip", "Cage Variant",
            "Photo-Painting", "Aluminum Print", "Squeegee Painting",
            "Atlas Page", "Portrait (Photo-Painting)",
        ],
        "filler_mediums": ["Oil on canvas", "Digital print on aluminum",
                           "Photo-painting", "Watercolor on paper"],
        "filler_dims": ["50x70", "120x100", "200x300", "300x300"],
        "filler_style": "Photo-peinture floutée et abstraction squeegee",
        "filler_year_range": (1962, 2022),
        "filler_owners_pool": ["Tate Modern", "MoMA", "Museum Ludwig",
                               "Centre Pompidou", "Fondation Beyeler",
                               "Collections privées internationales"],
    },
    "Koons": {
        "artist_id": "ART_KNS",
        "real_works": [
            ("Rabbit", 1986, "Stainless steel", "104x48x30",
             "Lapin gonflable en acier inoxydable. Vendu 91M$ Christie's 2019 (record artiste vivant).",
             "Sculpture pop métallique",
             "Édition de 3, plus AP. Sommet de la série Statuary.",
             "Collections privées multiples"),
            ("Balloon Dog (Orange)", 1994, "Stainless steel with mirror polish", "307x363x114",
             "Chien-ballon orange, série Celebration. Vendu 58M$ Christie's 2013.",
             "Sculpture monumentale Celebration",
             "Série Celebration, 5 couleurs. Acier poli miroir.",
             "Collection Pinault, Mugrabi, Eli Broad, etc."),
            ("Michael Jackson and Bubbles", 1988, "Porcelain, gold leaf", "107x180x76",
             "Sculpture porcelaine Michael Jackson et son chimpanzé.",
             "Sculpture pop kitsch série Banality",
             "Série Banality, édition de 3, scandale Madonna 1988.",
             "MOCA Los Angeles, Astrup Fearnley Museum"),
            ("Tulips", 2004, "Stainless steel with color coating", "203x457x520",
             "Bouquet de tulipes monumental série Celebration.",
             "Sculpture monumentale Celebration",
             "Série Celebration, dimensions monumentales.",
             "Collections privées multiples"),
            ("Hanging Heart (Magenta/Gold)", 2006, "Stainless steel", "291x280x101",
             "Cœur magenta suspendu, série Celebration.",
             "Sculpture monumentale Celebration",
             "Série Celebration, vendue 24M$ Sotheby's 2007.",
             "Collections privées"),
            ("Puppy", 1992, "Stainless steel and flowering plants", "1240x830x910",
             "Chien monumental floral installé Guggenheim Bilbao.",
             "Sculpture monumentale botanique",
             "Guggenheim Bilbao installation permanente.",
             "Guggenheim Bilbao"),
            ("Three Ball Total Equilibrium Tank", 1985, "Glass, water, basketballs", "153x124x33",
             "Trois ballons en suspension dans un aquarium série Equilibrium.",
             "Sculpture conceptuelle Equilibrium",
             "Série Equilibrium, première grande série Koons.",
             "Tate Modern, Whitney Museum"),
            ("Made in Heaven (Series)", 1991, "Multimedia", "various",
             "Série explicite avec La Cicciolina.",
             "Multimédia série Made in Heaven",
             "Série polémique avec son ex-épouse Ilona Staller.",
             "Diverses collections"),
            ("Gazing Ball (Apollo Citharoedus)", 2013, "Plaster and glass", "183x71x50",
             "Réplique sculpture antique avec ballon réfléchissant bleu.",
             "Sculpture appropriationiste",
             "Série Gazing Ball, classiques antiques.",
             "Collections privées"),
            ("Popeye", 2010, "Stainless steel with color coating", "152x131x71",
             "Personnage Popeye en acier coloré.",
             "Sculpture pop iconique",
             "Vendue 28M$ Sotheby's 2014.",
             "Collection Steve Wynn"),
        ],
        "filler_titles": [
            "Balloon Series", "Celebration Variant", "Made in Heaven Print",
            "Banality Series", "Equilibrium Tank", "Inflatable Sculpture",
            "Gazing Ball", "Popeye Variant",
        ],
        "filler_mediums": ["Stainless steel with color coating",
                           "Polychromed wood", "Mirror-polished steel",
                           "Porcelain, edition"],
        "filler_dims": ["100x80x40", "200x150x50", "300x300x100", "150x100x40"],
        "filler_style": "Sculpture pop kitsch et appropriation",
        "filler_year_range": (1985, 2022),
        "filler_owners_pool": ["Collection Pinault", "Whitney Museum",
                               "MOCA Los Angeles", "Astrup Fearnley Museum",
                               "Guggenheim Bilbao", "Collections privées Mugrabi"],
    },
    "Hirst": {
        "artist_id": "ART_HRS",
        "real_works": [
            ("The Physical Impossibility of Death in the Mind of Someone Living", 1991,
             "Tiger shark in formaldehyde", "213x518x213",
             "Requin en formol, œuvre emblématique YBA. Vendue 12M$ en 2004.",
             "Sculpture conceptuelle, série Natural History",
             "Œuvre fondatrice YBA. Saatchi commissioned.",
             "Collection Steve Cohen"),
            ("For the Love of God", 2007, "Platinum, diamonds, human skull", "17x12x19",
             "Crâne humain serti de 8601 diamants. Vendu 100M$ vers 2007.",
             "Sculpture conceptuelle memento mori",
             "Œuvre la plus chère jamais commissionnée.",
             "Collection privée"),
            ("Mother and Child Divided", 1993, "Cow and calf in formaldehyde", "190x400x86",
             "Vache et son veau coupés en deux dans formol.",
             "Sculpture conceptuelle Natural History",
             "Saatchi Gallery, série Natural History.",
             "Saatchi Gallery"),
            ("Spot Painting (Random)", 2007, "Household gloss on canvas", "152x122",
             "Tableau aux pois, série Spot Paintings.",
             "Spot Paintings, série emblématique",
             "Pratique d'atelier industrialisée, série de plusieurs milliers.",
             "Collections privées multiples"),
            ("Spin Painting (Beautiful)", 1995, "Household gloss on canvas", "(diameter 122)",
             "Peinture rotative, série Beautiful.",
             "Spin Paintings",
             "Série Beautiful, technique rotative.",
             "Collections privées multiples"),
            ("Away from the Flock", 1994, "Sheep in formaldehyde", "96x149x51",
             "Mouton en formol. Plusieurs versions vandalisées.",
             "Sculpture conceptuelle Natural History",
             "Plusieurs versions, dont une vandalisée 1994.",
             "Saatchi Gallery"),
            ("In and Out of Love", 1991, "Living butterflies installation", "various",
             "Installation papillons vivants.",
             "Installation Natural History",
             "Saatchi Gallery, polémique cruauté animale.",
             "Collections privées"),
            ("Lullaby Spring", 2002, "Cabinet with pills", "182x274x10",
             "Cabinet pharmacie aux pilules colorées.",
             "Cabinet pilules série Pharmacy",
             "Série Pharmacy, vendue 19M$ Sotheby's 2007.",
             "Collection privée"),
            ("Beautiful Inside My Head Forever", 2008, "Multiple lots", "various",
             "Vente directe Sotheby's, événement marché historique.",
             "Vente directe atelier",
             "Vente Sotheby's directe contournant les galeries 2008.",
             "Diverses collections"),
            ("Sympathy in White Major", 2006, "Butterflies on canvas", "152x152",
             "Composition papillons sur fond blanc.",
             "Butterfly Paintings",
             "Série Butterflies, références Damien Hirst.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Spot Painting", "Spin Painting", "Butterfly Variant",
            "Skull Series", "Pharmacy Cabinet", "Veil Painting",
            "The Currency", "Natural History Specimen",
        ],
        "filler_mediums": ["Household gloss on canvas", "Mixed media",
                           "Animal in formaldehyde", "Print on paper, signed edition"],
        "filler_dims": ["122x152", "152x152", "200x300", "diameter 122"],
        "filler_style": "Conceptuel YBA, signature Hirst",
        "filler_year_range": (1988, 2022),
        "filler_owners_pool": ["Saatchi Gallery", "Tate Modern",
                               "Collection Steve Cohen", "Collections privées Mugrabi",
                               "Collections privées internationales"],
    },
    "Bourgeois": {
        "artist_id": "ART_BRG",
        "real_works": [
            ("Maman", 1999, "Bronze, stainless steel, marble", "927x891x1023",
             "Araignée monumentale, hommage à sa mère. Édition de 6.",
             "Sculpture monumentale Spider",
             "Édition Maman, monumentale, dans plusieurs musées.",
             "Tate Modern, Guggenheim Bilbao, Mori Art Museum, etc."),
            ("Spider", 1996, "Bronze with silver nitrate patina", "326x756x686",
             "Araignée bronze, série Spider.",
             "Sculpture Spider",
             "Série déclinée en plusieurs tailles.",
             "Collections multiples"),
            ("Cell (Choisy)", 1990, "Mixed media installation", "300x300x300",
             "Cellule architecturale fragments enfance.",
             "Cells, série installation",
             "Série Cells, mémoire enfance Choisy-le-Roi.",
             "Diverses collections institutionnelles"),
            ("The Destruction of the Father", 1974, "Mixed media installation", "238x363x249",
             "Installation viscérale, table familiale en latex et résine.",
             "Installation psychanalytique",
             "Œuvre fondatrice psychanalyse Bourgeois.",
             "Hauser & Wirth Collection"),
            ("Femme Maison", 1946, "Oil on canvas", "92x36",
             "Femme dont la tête est une maison, série emblématique.",
             "Femme Maison, série emblématique",
             "Série Femme Maison, archétype féministe.",
             "MoMA New York"),
            ("Cumul I", 1969, "Marble", "57x127x122",
             "Formes mammaires en marbre.",
             "Sculpture marbre, série Cumul",
             "Période sculpture sensuelle marbre.",
             "Centre Pompidou"),
            ("Eyes", 1982, "Carrara marble", "190x140x170",
             "Yeux monumentaux en marbre.",
             "Sculpture marbre",
             "Période exploration des yeux comme symbole.",
             "Collections privées"),
            ("Spiral Woman", 1984, "Bronze and steel cable", "121x76x76",
             "Femme suspendue en spirale.",
             "Sculpture suspendue",
             "Série Spiral Woman, féminité contrainte.",
             "Collection privée"),
            ("Cell (Hands and Mirror)", 1995, "Mixed media installation", "200x200x150",
             "Cellule mains et miroir.",
             "Cells, série installation",
             "Série Cells, espaces psychanalytiques.",
             "Diverses collections institutionnelles"),
            ("Couple IV", 1997, "Fabric", "50x150x100",
             "Couple en tissu, série fin de carrière.",
             "Sculpture textile tardive",
             "Période Couples textiles, fin carrière.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Spider Variant", "Cell Installation", "Femme Maison Variant",
            "Cumul Series", "Drawing Suite", "Personage",
            "Couple Series", "Untitled (Drawing)",
        ],
        "filler_mediums": ["Bronze with patina", "Marble carved",
                           "Mixed media installation", "Watercolor on paper",
                           "Fabric and metal"],
        "filler_dims": ["50x70x40", "120x80x60", "200x150x100", "300x300x250"],
        "filler_style": "Sculpture psychanalytique et textile",
        "filler_year_range": (1940, 2010),
        "filler_owners_pool": ["Tate Modern", "Centre Pompidou",
                               "MoMA", "Hauser & Wirth Collection",
                               "Collections privées internationales"],
    },
    # ───── PHOTOGRAPHY ─────
    "Cindy Sherman": {
        "artist_id": "ART_CSH",
        "real_works": [
            ("Untitled #96", 1981, "Chromogenic print, edition of 10", "61x122",
             "Centerfolds Series. Vendue 3,89M$ Christie's 2011 (record photo à l'époque).",
             "Photographie mise en scène, Centerfolds Series",
             "Série Centerfolds, commande Artforum 1981.",
             "Diverses collections institutionnelles"),
            ("Untitled Film Still #21", 1978, "Gelatin silver print, edition", "20x25",
             "Untitled Film Stills, série fondatrice.",
             "Photographie mise en scène, Untitled Film Stills",
             "Série fondatrice 70 photos imitant le cinéma.",
             "MoMA, Centre Pompidou"),
            ("History Portraits #209 (Madame Pompadour)", 1989, "Color photograph", "172x122",
             "Détournement Madame de Pompadour, série History Portraits.",
             "History Portraits",
             "Série History Portraits, commande Limoges 1989.",
             "Collections privées"),
            ("Society Portraits", 2008, "Chromogenic print", "172x150",
             "Société grande bourgeoise vieillissante, série Society.",
             "Society Portraits",
             "Série Society Portraits.",
             "Collections privées"),
            ("Clown Series Untitled #424", 2004, "Chromogenic print", "147x102",
             "Clown grotesque série Clowns.",
             "Clown Series",
             "Série Clowns, exploration du grotesque.",
             "Collections privées"),
            ("Sex Pictures (#250)", 1992, "Chromogenic print", "127x190",
             "Mannequins disloqués série Sex Pictures.",
             "Sex Pictures",
             "Série polémique mannequins assemblés.",
             "Collections privées"),
            ("Disasters (#244)", 1986, "Chromogenic print", "120x180",
             "Visions cauchemardesques série Disasters.",
             "Disasters",
             "Série Disasters/Fairy Tales.",
             "Collections privées"),
            ("Untitled #305 (Hollywood Hampton Type)", 2003, "Chromogenic print", "127x91",
             "Femmes Hollywood vieillissantes.",
             "Hollywood/Hampton Types",
             "Série Hollywood/Hampton.",
             "Collections privées"),
            ("Murder Mystery #103", 1976, "Gelatin silver print", "20x25",
             "Mise en scène cinéma, période étudiante.",
             "Première période, Murder Mystery",
             "Période formative, Murder Mystery.",
             "Collections privées"),
            ("Untitled #155", 1985, "Color photograph", "184x125",
             "Étendue dans paysage post-apocalyptique.",
             "Disasters period",
             "Période Disasters/Fairy Tales.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Untitled (Film Stills variant)", "Centerfolds variant",
            "History Portrait", "Society Portrait", "Clown",
            "Disaster", "Murder Mystery", "Untitled #",
        ],
        "filler_mediums": ["Chromogenic print, edition", "Gelatin silver print, edition",
                           "Inkjet print on paper, signed edition"],
        "filler_dims": ["50x70", "100x150", "150x100", "180x130"],
        "filler_style": "Photographie mise en scène, identité multiple",
        "filler_year_range": (1975, 2022),
        "filler_owners_pool": ["MoMA", "Tate Modern", "Centre Pompidou",
                               "Whitney Museum", "Collections privées multiples"],
    },
    "Gursky": {
        "artist_id": "ART_GRS",
        "real_works": [
            ("Rhein II", 1999, "C-print, edition of 6", "186x364",
             "Paysage minimal Rhin. Record monde photo 4,3M$ Christie's 2011.",
             "Photographie typologique Düsseldorf School",
             "Édition de 6, dont une au MoMA.",
             "MoMA, Tate Modern, Glenstone Museum, Pinakothek"),
            ("99 Cent II Diptych", 2001, "C-print, edition", "207x336",
             "Supermarché 99 cents stylisé. Vendu 3,3M$ Sotheby's 2007.",
             "Photographie économie globalisée",
             "Édition de 6, série commerce mondialisé.",
             "Diverses collections institutionnelles"),
            ("Chicago Board of Trade III", 1999, "C-print", "187x340",
             "Salle de marchés Chicago, séries Stock Exchange.",
             "Photographie économie globalisée",
             "Série Stock Exchanges.",
             "Tate Modern"),
            ("Bahrain I", 2007, "C-print", "300x222",
             "Circuit Formule 1 Bahrain, géométrie aérienne.",
             "Photographie aérienne paysage",
             "Édition limitée.",
             "Collections privées"),
            ("Pyongyang IV", 2007, "C-print", "300x215",
             "Mass Games Corée du Nord, ordre totalitaire.",
             "Photographie politique mass",
             "Série Pyongyang, observée Corée du Nord.",
             "Collections multiples"),
            ("Tokyo Stock Exchange", 1990, "C-print", "187x238",
             "Salle de bourse Tokyo, première période.",
             "Photographie économie",
             "Série Stock Exchanges.",
             "Collection Goetz"),
            ("Ocean II", 2010, "C-print", "330x227",
             "Vue satellite océanique, série Ocean.",
             "Photographie satellite",
             "Série Ocean, photographies satellites composées.",
             "Collections privées"),
            ("Rave", 1995, "C-print", "176x256",
             "Foule en discothèque, période rave.",
             "Photographie sociale",
             "Période rave berlinoise.",
             "Collections privées"),
            ("Madonna I", 2001, "C-print", "289x208",
             "Concert Madonna, foule en effervescence.",
             "Photographie spectacle",
             "Série Concerts.",
             "Collection Pinault"),
            ("Bangkok IX", 2011, "C-print", "300x223",
             "Vue aérienne Chao Phraya, traînées colorées.",
             "Photographie paysage urbain",
             "Série Bangkok, paysages urbains.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Stock Exchange", "Ocean Series", "Untitled (Aerial)",
            "Mass Games", "Concert", "Architectural Study",
            "Untitled (Düsseldorf School)",
        ],
        "filler_mediums": ["C-print, edition of 6", "Inkjet print, edition",
                           "C-print mounted on Plexiglas"],
        "filler_dims": ["180x240", "200x300", "270x350", "300x220"],
        "filler_style": "Photographie typologique Düsseldorf School",
        "filler_year_range": (1985, 2022),
        "filler_owners_pool": ["MoMA", "Tate Modern", "Centre Pompidou",
                               "Glenstone Museum", "Pinakothek der Moderne",
                               "Collections privées internationales"],
    },
    "Nan Goldin": {
        "artist_id": "ART_NGD",
        "real_works": [
            ("Nan and Brian in Bed, NYC", 1983, "Cibachrome print, edition", "76x102",
             "The Ballad of Sexual Dependency, œuvre emblématique.",
             "Photographie intime documentaire",
             "Œuvre centrale Ballad of Sexual Dependency 1986.",
             "MoMA, Whitney Museum"),
            ("Nan One Month After Being Battered", 1984, "Cibachrome print", "76x102",
             "Auto-portrait après agression de son compagnon.",
             "Photographie auto-référentielle",
             "Période violente, dénonciation directe.",
             "MoMA, Tate Modern"),
            ("Self-Portrait in Kimono with Brian", 1983, "Cibachrome print", "76x102",
             "Auto-portrait au kimono.",
             "Photographie intime",
             "Période Bowery, NYC.",
             "Collections privées"),
            ("Honda brothers in Cha-cha-cha club, Bangkok", 1992, "Cibachrome print", "76x102",
             "Communauté drag asiatique.",
             "Photographie communauté queer",
             "Série Bangkok, communauté drag asiatique.",
             "Collections privées"),
            ("Greer and Robert on the bed, NYC", 1982, "Cibachrome print", "76x102",
             "Couple sur le lit, série Ballad.",
             "Photographie intime",
             "The Ballad of Sexual Dependency.",
             "Collections privées"),
            ("Cookie Mueller in pink robe", 1982, "Cibachrome print", "76x102",
             "Cookie Mueller, performeuse iconique.",
             "Photographie portrait communauté",
             "Cookie Mueller, performeuse John Waters.",
             "Collections privées"),
            ("Sister Goldin", 1981, "Cibachrome print", "76x102",
             "Photographie de famille reconstituée.",
             "Photographie intime familiale",
             "Référence à sa sœur Barbara, suicide d'enfance.",
             "Collections privées"),
            ("Misty and Jimmy Paulette in a Taxi", 1991, "Cibachrome print", "76x102",
             "Drag queens dans un taxi NYC.",
             "Photographie communauté queer",
             "Période documentation drag NYC.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Ballad Variant", "Bowery Series", "Drag Queen Portrait",
            "Self-Portrait", "Friends in Bed", "Nightlife",
            "Untitled (Couple)", "Bangkok Series",
        ],
        "filler_mediums": ["Cibachrome print, edition", "Slideshow installation",
                           "Inkjet print on paper, edition"],
        "filler_dims": ["76x102", "100x150", "120x180"],
        "filler_style": "Photographie intime documentaire",
        "filler_year_range": (1979, 2022),
        "filler_owners_pool": ["MoMA", "Tate Modern", "Whitney Museum",
                               "Centre Pompidou", "Collections privées"],
    },
    "Richard Prince": {
        "artist_id": "ART_RPR",
        "real_works": [
            ("Untitled (Cowboy)", 1989, "Ektacolor print, edition", "127x178",
             "Détournement publicité Marlboro Man. Vendu 3,4M$ Christie's 2014.",
             "Appropriation, série Cowboys",
             "Série Cowboys, photographies de Marlboro Man réappropriées.",
             "Collections privées"),
            ("Spiritual America", 1983, "Ektacolor print", "61x51",
             "Brooke Shields nue à 10 ans, photo réappropriée. Polémique majeure.",
             "Appropriation polémique",
             "Polémique majeure, photographie originale Garry Gross.",
             "Collections multiples (controversies)"),
            ("Untitled (Joke)", 1989, "Acrylic and silkscreen on canvas", "152x102",
             "Texte de blague typographique sur fond monochrome.",
             "Joke Paintings",
             "Série Jokes, texte appropriationiste.",
             "Collections privées"),
            ("Nurse Painting", 2002, "Inkjet on canvas", "183x122",
             "Couverture pulp roman infirmière retouchée.",
             "Nurse Paintings",
             "Série Nurses, romans-photos pulp.",
             "Collections privées"),
            ("New Portraits (Instagram)", 2014, "Inkjet on canvas", "168x122",
             "Captures Instagram d'inconnus, séries polémique.",
             "New Portraits",
             "Polémique appropriation Instagram 2014.",
             "Collections privées"),
            ("Cowboy Series #4", 1987, "Ektacolor print", "120x180",
             "Cowboy Marlboro Man variation.",
             "Cowboys Series",
             "Série Cowboys.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Cowboy Series", "Joke Painting", "Nurse Painting",
            "Untitled (Hood)", "New Portrait", "Marlboro Series",
            "Untitled (Joke)", "Untitled (Girlfriend)",
        ],
        "filler_mediums": ["Ektacolor print, edition", "Acrylic and silkscreen",
                           "Inkjet print on canvas, edition"],
        "filler_dims": ["120x180", "152x102", "168x122", "200x150"],
        "filler_style": "Appropriation et culture pop USA",
        "filler_year_range": (1980, 2022),
        "filler_owners_pool": ["MoMA", "Whitney Museum",
                               "Collection Mugrabi", "Collections privées"],
    },
    "Tillmans": {
        "artist_id": "ART_TLM",
        "real_works": [
            ("Lutz & Alex sitting in the trees", 1992, "Inkjet print, edition", "61x51",
             "Premier travail Tillmans, ses amis dans un arbre.",
             "Photographie intime communauté",
             "Œuvre fondatrice première période.",
             "Tate Modern"),
            ("Freischwimmer", 2003, "Inkjet print, edition", "180x140",
             "Image abstraite sans appareil photo.",
             "Photographie abstraite Freischwimmer",
             "Série Freischwimmer, abstraction sans caméra.",
             "Collections multiples"),
            ("Paper Drop", 1999, "Inkjet print", "61x51",
             "Feuille papier en chute, série Paper Drop.",
             "Photographie minimaliste",
             "Série Paper Drop, contemplation papier.",
             "Tate Modern"),
            ("Concorde Grid", 1997, "Inkjet print", "30x40 (each)",
             "Grille de 56 photographies Concorde.",
             "Photographie installation grid",
             "Série Concorde, fascination technologie.",
             "Tate Modern"),
            ("Zimmerlinde (Ulm)", 2007, "Inkjet print", "200x140",
             "Tilleul nocturne, paysage urbain.",
             "Photographie paysage",
             "Série paysages urbains nocturnes.",
             "Collection privée"),
            ("Headlight (a)", 2012, "Inkjet print", "180x140",
             "Phare voiture nuit, abstraction lumineuse.",
             "Photographie abstraite",
             "Période exploration lumière.",
             "Collection privée"),
            ("Adam, Red Eye", 1991, "Inkjet print", "30x40",
             "Portrait Adam, période early.",
             "Photographie portrait communauté",
             "Période early communauté.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Freischwimmer Variant", "Paper Drop Variant",
            "Untitled (Portrait)", "Astro Crusto", "Sound Installation",
            "Astro Crusto a", "Lighter",
        ],
        "filler_mediums": ["Inkjet print, edition", "C-print, edition",
                           "Light installation"],
        "filler_dims": ["30x40", "61x51", "120x180", "180x250"],
        "filler_style": "Photographie multidisciplinaire et abstraction",
        "filler_year_range": (1989, 2022),
        "filler_owners_pool": ["Tate Modern", "MoMA", "Centre Pompidou",
                               "Sammlung Goetz", "Collections privées"],
    },
    # ───── ULTRA-CONTEMPORARY ─────
    "Avery Singer": {
        "artist_id": "ART_AVS",
        "real_works": [
            ("Free Fall", 2017, "Acrylic on canvas", "210x280",
             "Composition figurative générée Sketchup, signature airbrush.",
             "Peinture digitale Sketchup",
             "Période Sketchup mature, sommet série Free Fall.",
             "Collections privées"),
            ("Studio Visit", 2014, "Acrylic on canvas", "239x179",
             "Studio visit imaginaire, composition cubiste digitale.",
             "Peinture digitale Sketchup",
             "Période Whitney Biennial.",
             "Whitney Museum"),
            ("Disco Inferno", 2018, "Acrylic on canvas", "239x239",
             "Discothèque imaginaire airbrush.",
             "Peinture digitale airbrush",
             "Période Hauser & Wirth signing.",
             "Collections privées"),
            ("Performance Artists", 2013, "Acrylic on canvas", "180x180",
             "Artistes performance imaginaires.",
             "Peinture digitale Sketchup",
             "Période early career.",
             "Collections privées"),
            ("Brain Trust", 2019, "Acrylic on canvas", "239x192",
             "Cerveaux flottants composition airbrush.",
             "Peinture digitale airbrush",
             "Période apogée Hauser & Wirth.",
             "Collection privée"),
            ("Reclining Nude", 2016, "Acrylic on canvas", "172x239",
             "Nu allongé digital airbrush.",
             "Peinture digitale Sketchup",
             "Période transition Hauser & Wirth.",
             "Collections privées"),
        ],
        "filler_titles": [
            "Untitled (Sketchup)", "Studio Variant",
            "Disco Series", "Brain Series", "Performance Variant",
            "Reclining Series", "Architectural Study",
        ],
        "filler_mediums": ["Acrylic on canvas", "Acrylic and airbrush on canvas"],
        "filler_dims": ["152x152", "180x180", "210x280", "240x300"],
        "filler_style": "Peinture digitale Sketchup, airbrush",
        "filler_year_range": (2011, 2022),
        "filler_owners_pool": ["Whitney Museum", "Collection Pinault",
                               "Hauser & Wirth Collection",
                               "Stedelijk Museum", "Collections privées"],
    },
    "Flora Yukhnovich": {
        "artist_id": "ART_FYK",
        "real_works": [
            ("I'll Have What She's Having", 2020, "Oil on linen", "200x250",
             "Détournement Rococo, sommet ventes Sotheby's 2022 (3M£).",
             "Néo-Rococo abstrait",
             "Période apogée commerciale.",
             "Collection privée"),
            ("Tu vas me faire pleurer", 2019, "Oil on canvas", "190x230",
             "Période Rococo gestuelle expressive.",
             "Néo-Rococo abstrait",
             "Période early Yukhnovich.",
             "Collections privées"),
            ("Pretty Little Thing", 2021, "Oil on linen", "200x250",
             "Composition rose pastel.",
             "Néo-Rococo abstrait pastel",
             "Période Sotheby's apogée.",
             "Collection privée"),
            ("Where Did You Sleep Last Night", 2020, "Oil on linen", "180x220",
             "Composition gestuelle dramatique.",
             "Néo-Rococo gestuel",
             "Période commerciale apogée.",
             "Collection privée"),
            ("Pour les fêtes", 2021, "Oil on canvas", "150x190",
             "Composition fêtes galantes Watteau réinterprétées.",
             "Néo-Rococo Watteau",
             "Période Watteau réinterprété.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Untitled (Rococo Series)", "Cherub Variant",
            "Pastel Composition", "Watteau Variant",
            "Untitled (Pink)", "Garden Scene",
        ],
        "filler_mediums": ["Oil on linen", "Oil on canvas",
                           "Oil and gesso on canvas"],
        "filler_dims": ["150x190", "180x220", "200x250", "240x300"],
        "filler_style": "Néo-Rococo abstrait, palette pastel",
        "filler_year_range": (2017, 2022),
        "filler_owners_pool": ["Collections privées asiatiques",
                               "Victoria Miro Collection",
                               "Collections privées européennes"],
    },
    "Jade Fadojutimi": {
        "artist_id": "ART_JDF",
        "real_works": [
            ("A Vortex of Pillows", 2020, "Oil and oilstick on canvas", "200x200",
             "Composition gestuelle abstraction lyrique. Vendue 720K€ Phillips 2022.",
             "Abstraction lyrique post-2018",
             "Période Gagosian apogée.",
             "Collections privées"),
            ("Sapphire Yawning", 2019, "Oil on canvas", "200x230",
             "Composition gestuelle bleue intense.",
             "Abstraction lyrique",
             "Période Pippy Houldsworth.",
             "Collection privée"),
            ("Myths of Pleasure (B)", 2021, "Oil and oilstick on canvas", "180x230",
             "Composition gestuelle, série Myths of Pleasure.",
             "Abstraction lyrique gestuelle",
             "Période Gagosian.",
             "Collection privée"),
            ("In a Pillow with Crashing Waves", 2020, "Oil on canvas", "180x230",
             "Période apogée gestuelle abstraction.",
             "Abstraction lyrique",
             "Période Gagosian commerciale.",
             "Collection privée"),
            ("Crashing into the Realm of Indecision", 2021, "Oil and oilstick on canvas", "200x300",
             "Composition gestuelle ample.",
             "Abstraction lyrique grande échelle",
             "Période Hepworth Wakefield show.",
             "Collection institutionnelle"),
        ],
        "filler_titles": [
            "Untitled (Lyrical Abstraction)", "Vortex Variant",
            "Pleasure Series", "Pillow Series", "Wave Series",
            "Untitled (Pastel)", "Composition (Oil and Oilstick)",
        ],
        "filler_mediums": ["Oil on canvas", "Oil and oilstick on canvas",
                           "Watercolor on paper"],
        "filler_dims": ["150x200", "180x230", "200x300", "240x300"],
        "filler_style": "Abstraction lyrique gestuelle post-2018",
        "filler_year_range": (2017, 2022),
        "filler_owners_pool": ["Hepworth Wakefield", "Pippy Houldsworth Collection",
                               "Collections privées internationales"],
    },
    "Matthew Wong": {
        "artist_id": "ART_MWG",
        "real_works": [
            ("River at Dusk", 2018, "Oil on canvas", "203x152",
             "Paysage onirique, période emblématique. Œuvre clé Karma.",
             "Paysage onirique néo-expressionniste",
             "Karma NY, période apogée 2018-2019.",
             "Collection privée"),
            ("The Realm of Appearances", 2018, "Oil on canvas", "203x178",
             "Paysage habité, palette violet bleu.",
             "Paysage onirique",
             "Période Karma apogée.",
             "Collection privée"),
            ("Footprints in the Wind", 2019, "Oil on canvas", "180x150",
             "Paysage solitaire dépouillé.",
             "Paysage onirique mélancolique",
             "Dernière période, peu avant son suicide.",
             "Collection privée"),
            ("Night Garden", 2017, "Oil on canvas", "152x122",
             "Jardin nocturne, période early Karma.",
             "Paysage onirique nocturne",
             "Période early Karma signing.",
             "Collection privée"),
            ("The Kingdom", 2017, "Oil on canvas", "180x230",
             "Composition paysage royaume imaginaire.",
             "Paysage onirique",
             "Première grande exposition Karma.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Untitled (Landscape)", "Forest Series",
            "Night Series", "Untitled (Blue)",
            "Garden Series", "Pond Series", "Mountain Study",
        ],
        "filler_mediums": ["Oil on canvas", "Gouache on paper",
                           "Ink on paper"],
        "filler_dims": ["100x80", "150x120", "180x230", "200x152"],
        "filler_style": "Paysage onirique néo-expressionniste",
        "filler_year_range": (2015, 2019),
        "filler_owners_pool": ["Karma Gallery archives",
                               "Estate of Matthew Wong",
                               "Collections privées internationales"],
    },
    "Yoshitomo Nara": {
        "artist_id": "ART_YSN",
        "real_works": [
            ("Knife Behind Back", 2000, "Acrylic on canvas", "234x208",
             "Petite fille au couteau caché derrière le dos. Vendue 25M$ Sotheby's HK 2019.",
             "Pop figuratif manga subversif",
             "Période Yokohama, sommet série défi.",
             "Collection privée asiatique"),
            ("Marching On a Butterbur Leaf", 1990, "Acrylic on canvas", "260x195",
             "Petite figure marchant, période early Düsseldorf.",
             "Pop figuratif manga early",
             "Période Düsseldorf, formation européenne.",
             "Collections privées"),
            ("Pyromaniac Dead of Night", 1999, "Acrylic on canvas", "150x130",
             "Petite fille pyromane série Dead of Night.",
             "Pop figuratif subversif",
             "Période Yokohama apogée.",
             "Collection privée"),
            ("Hothouse Doll", 2005, "Acrylic on canvas", "160x142",
             "Petite fille tendre série Hothouse.",
             "Pop figuratif manga",
             "Période transition tendresse.",
             "Collection privée"),
            ("Miss Forest", 2010, "Bronze sculpture", "170x80x70",
             "Sculpture monumentale, série Miss Forest.",
             "Sculpture pop figuratif",
             "Série Miss Forest, multiples versions.",
             "Diverses collections institutionnelles"),
            ("Untitled (After the Acid Rain)", 2007, "Acrylic on canvas", "180x140",
             "Petite fille post-apocalyptique.",
             "Pop figuratif manga",
             "Série préoccupation environnementale.",
             "Collection privée"),
        ],
        "filler_titles": [
            "Little Girl Variant", "Untitled (Bronze)",
            "Knife Series", "Hothouse Variant",
            "Eye Patch Girl", "Untitled (Sketch)",
        ],
        "filler_mediums": ["Acrylic on canvas", "Bronze sculpture",
                           "Pencil and crayon on paper"],
        "filler_dims": ["100x80", "150x130", "180x140", "240x200"],
        "filler_style": "Pop figuratif manga, palette pastel",
        "filler_year_range": (1988, 2022),
        "filler_owners_pool": ["Yokohama Museum of Art",
                               "Mori Art Museum",
                               "Collections privées asiatiques",
                               "Pace Gallery archives"],
    },
}

CATEGORY_BY_ARTIST = {
    "Banksy": "Street Art", "KAWS": "Street Art", "Invader": "Street Art",
    "Mr. Brainwash": "Street Art", "Shepard Fairey": "Street Art",
    "Picasso": "Blue Chip", "Warhol": "Blue Chip", "Monet": "Blue Chip",
    "Basquiat": "Blue Chip", "Giacometti": "Blue Chip",
    "Hockney": "Modern Masters", "Richter": "Modern Masters", "Koons": "Modern Masters",
    "Hirst": "Modern Masters", "Bourgeois": "Modern Masters",
    "Cindy Sherman": "Photography", "Gursky": "Photography", "Nan Goldin": "Photography",
    "Richard Prince": "Photography", "Tillmans": "Photography",
    "Avery Singer": "Ultra-Contemporary", "Flora Yukhnovich": "Ultra-Contemporary",
    "Jade Fadojutimi": "Ultra-Contemporary", "Matthew Wong": "Ultra-Contemporary",
    "Yoshitomo Nara": "Ultra-Contemporary",
}


def load_constraints() -> dict[str, str]:
    """Return {artwork_id: earliest_sale_date} from the sales CSV."""
    earliest: dict[str, str] = {}
    with SALES_CSV.open() as f:
        for r in csv.DictReader(f):
            aid, d = r["artwork_id"], r["sale_date"]
            if aid not in earliest or d < earliest[aid]:
                earliest[aid] = d
    return earliest


def order_artworks_per_artist() -> dict[str, list[str]]:
    """Return {artist_name: [artwork_id, ...]} ordered by id."""
    result: dict[str, list[str]] = defaultdict(list)
    with SALES_CSV.open() as f:
        seen: set[str] = set()
        for r in csv.DictReader(f):
            aid = r["artwork_id"]
            if aid in seen:
                continue
            seen.add(aid)
            result[r["artist_name"]].append(aid)
    for k in result:
        result[k].sort()
    return result


def gen_filler(artist: str, slot: int, max_year: int) -> tuple[str, int, str, str, str, str, str, str]:
    cfg = ARTIST_DATA[artist]
    rnd = random.Random(f"{artist}:{slot}")
    title_base = rnd.choice(cfg["filler_titles"])
    if title_base.endswith(("Series", "Variant", "Print", "Painting", "Edition", "Study", "Painting)", "Drawing")):
        title = f"{title_base} #{slot:02d}"
    elif title_base.endswith("_"):
        title = f"{title_base}{slot:04d}"
    elif "(" in title_base and ")" in title_base:
        title = title_base
    else:
        title = f"{title_base} ({slot:02d})"
    yr_lo, yr_hi = cfg["filler_year_range"]
    yr_hi = min(yr_hi, max_year)
    yr_lo = min(yr_lo, yr_hi)
    year = rnd.randint(yr_lo, yr_hi)
    medium = rnd.choice(cfg["filler_mediums"])
    dims = rnd.choice(cfg["filler_dims"])
    desc = (
        f"{title}, exécutée par {artist} en {year}. "
        f"Œuvre dans le style caractéristique de l'artiste, support {medium.lower()}."
    )
    style = cfg["filler_style"]
    context = f"Période créative {year}, série stylistique caractéristique."
    owners = rnd.choice(cfg["filler_owners_pool"])
    return title, year, medium, dims, desc, style, context, owners


def gen_bart_score(artist: str, is_real: bool, slot: int) -> int:
    rnd = random.Random(f"score:{artist}:{slot}")
    if is_real:
        return rnd.randint(82, 95)
    return rnd.randint(70, 88)


def main() -> None:
    earliest = load_constraints()
    order = order_artworks_per_artist()

    rows: list[dict] = []
    for artist, ids in order.items():
        if artist not in ARTIST_DATA:
            raise SystemExit(f"Missing ARTIST_DATA for: {artist}")
        cfg = ARTIST_DATA[artist]
        cat = CATEGORY_BY_ARTIST[artist]
        artist_id = cfg["artist_id"]
        real = cfg["real_works"]

        for slot, aid in enumerate(ids):
            earliest_sale = earliest[aid]
            max_year = int(earliest_sale.split("-")[0])

            if slot < len(real):
                title, year, medium, dims, desc, style, context, owners = real[slot]
                # Constrain year to be <= earliest sale year
                if year > max_year:
                    year = max_year - 1
                is_real = True
            else:
                title, year, medium, dims, desc, style, context, owners = gen_filler(
                    artist, slot - len(real), max_year
                )
                is_real = False

            rows.append({
                "artwork_id": aid,
                "artist_name": artist,
                "artist_id": artist_id,
                "category": cat,
                "title": title,
                "year_created": year,
                "medium": medium,
                "dimensions_cm": dims,
                "description": desc,
                "creation_context": context,
                "artwork_style": style,
                "notable_owners": owners,
                "bart_score": gen_bart_score(artist, is_real, slot),
                "image_url": "",
            })

    fieldnames = list(rows[0].keys())
    with OUT_CSV.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

    real_count = sum(1 for a, ids in order.items() for i, _ in enumerate(ids) if i < len(ARTIST_DATA[a]["real_works"]))
    print(f"✓ Wrote {len(rows)} rows to {OUT_CSV.relative_to(ROOT)}")
    print(f"  Real artworks: {real_count}")
    print(f"  Filler artworks: {len(rows) - real_count}")


if __name__ == "__main__":
    main()
